# Generated by Django 4.0.3 on 2022-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homenet',
            fields=[
                ('usr_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=100)),
                ('usr_package', models.CharField(max_length=100)),
                ('usr_designation', models.CharField(max_length=100)),
                ('usr_remain_amount', models.CharField(max_length=100)),
                ('usr_net_id', models.CharField(max_length=100)),
                ('usr_contact', models.CharField(max_length=100)),
                ('status_choice', models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('disabled/disconnected', 'DISABLED/DISCONNECTED'), ('active', 'ACTIVE')], default='pending', max_length=100)),
            ],
        ),
    ]
